"""No Steam ID belongs in this repo.

The save fixture is real data, so this is not a hypothetical: it is the one
rule a careless `cp` would break. A Steam ID is 17 digits, so anything shaped
that way in a tracked file fails here, with the documented placeholder as the
sole exception.

The pattern lives in `conftest.py`, since `test_progress.py` scans CLI output
for the same shape and the two must not drift apart. Its digit-boundary anchors
are load-bearing: the repo cites Steam forum and news URLs, whose thread ids are
longer than an account id, and an unanchored 17-digit window would match inside
every one of them.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from conftest import PLACEHOLDER_STEAM_ID, STEAM_ID_SHAPED, steam_ids_in

REPO_ROOT = Path(__file__).resolve().parent.parent

# A lockfile of hex digests, generated by uv from the package index. Digit runs
# inside a digest are noise, and no Steam ID can arrive there.
GENERATED = {"uv.lock"}


def _tracked_files() -> list[Path]:
    listing = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [
        REPO_ROOT / name
        for name in listing.stdout.split("\0")
        if name and name not in GENERATED
    ]


def test_no_tracked_file_contains_something_shaped_like_a_steam_id() -> None:
    offenders = []
    for path in _tracked_files():
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if steam_ids_in(content):
            offenders.append(path.relative_to(REPO_ROOT))
    assert not offenders, f"Steam-ID-shaped digits in tracked files: {offenders}"


def test_no_tracked_path_is_named_after_a_real_steam_id() -> None:
    offenders = [
        path.relative_to(REPO_ROOT)
        for path in _tracked_files()
        if any(
            STEAM_ID_SHAPED.fullmatch(part) and part != PLACEHOLDER_STEAM_ID
            for part in path.parts
        )
    ]
    assert not offenders, f"Steam-ID-shaped path segments: {offenders}"


def test_a_longer_digit_run_is_not_a_steam_id() -> None:
    """A 19-digit Steam thread id is not an account id, and must not be flagged."""
    thread_url = (
        "https://steamcommunity.com/app/1942280/discussions/0/3811786447112952913/"
    )
    assert steam_ids_in(thread_url) == set()


def test_a_bare_steam_id_is_still_an_offender() -> None:
    # Assembled rather than written out: a literal 17-digit run in this file
    # would make the test file its own offender.
    account_id = "76561198" + "0" * 9
    assert steam_ids_in(f"id {account_id} here") == {account_id}


def test_the_placeholder_is_exempt() -> None:
    assert steam_ids_in(PLACEHOLDER_STEAM_ID) == set()
