"""No Steam ID belongs in this repo.

The save fixture is real data, so this is not a hypothetical: it is the one
rule a careless `cp` would break. A Steam ID is 17 digits, so anything shaped
that way in a tracked file fails here, with the documented placeholder as the
sole exception.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STEAM_ID_SHAPED = re.compile(r"\d{17}")
PLACEHOLDER = "0" * 17

# A lockfile of hex digests, generated by uv from the package index. Digit runs
# inside a digest are noise, and no Steam ID can arrive there.
GENERATED = {"uv.lock"}


def _tracked_files() -> list[Path]:
    listing = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [
        REPO_ROOT / name
        for name in listing.stdout.split("\0")
        if name and name not in GENERATED
    ]


def test_no_tracked_file_contains_something_shaped_like_a_steam_id() -> None:
    offenders = []
    for path in _tracked_files():
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        found = {
            match for match in STEAM_ID_SHAPED.findall(content) if match != PLACEHOLDER
        }
        if found:
            offenders.append(path.relative_to(REPO_ROOT))
    assert not offenders, f"Steam-ID-shaped digits in tracked files: {offenders}"


def test_no_tracked_path_is_named_after_a_real_steam_id() -> None:
    offenders = [
        path.relative_to(REPO_ROOT)
        for path in _tracked_files()
        if any(
            STEAM_ID_SHAPED.fullmatch(part) and part != PLACEHOLDER
            for part in path.parts
        )
    ]
    assert not offenders, f"Steam-ID-shaped path segments: {offenders}"
